"""Batch-3 reconciliation of handoff.json to disk (Nova, W37, 7 Sep).

One atomic pass: sync approved captions to disk files, write truthful blocked
entries and generation meta, refresh blockers/verified. Run once; it is not
idempotent by design (blocked reasons are statements about this run).
"""
import json, pathlib

HF = pathlib.Path(__file__).parent / "handoff.json"
j = json.loads(HF.read_text(encoding="utf-8"))
ROOT = HF.parents[2]           # personas/seoyeon
CAPS = ROOT / "caps"

# ---- 1. sync captions of approved shots to disk, file-for-file ----
for e in j["entries"]:
    cid = e["id"]
    disk = (CAPS / f"{cid}.txt").read_text(encoding="utf-8")
    j["captions"][cid] = disk.rstrip("\n")

# ---- 2. blocked, truthful, per disk ----
MKT = "content" + chr(92) + "w37_2026-09-07" + chr(92) + "w37_market_peaches_421923_1.png"
j["blocked"] = [
  {
    "id": "w37_jieun_roof",
    "tier": 1,
    "lanes": ["instagram"],
    "media_file": None,
    "caption_file": None,
    "publish_at": "2026-09-10T20:40+09:00",
    "render_approved": False,
    "renders_available": 0,
    "reason": ("RE-SPECIFIED 7 Sep (owner 3-faces ruling): the shot now carries her face. "
      "Jieun is the camera, never a rendered person — the shipped n_cafe_jieun precedent, "
      "where the second cup nearest the lens is where Jieun sits. The old cups-only render "
      "(w37_jieun_roof_bd67ba_1.png, generated from the noface spec) cannot carry her face "
      "and was deleted as spec-superseded. NOT REGENERATED THIS RUN: this session's model "
      "has no image support, so no render could be reviewed or approved, and generating "
      "unreviewable renders would recreate the state that stalled this week. Spec is final "
      "and dry-run validated in w37_shots.py (plate_rooftop, safe=True, face refs Images 2-3). "
      "NEXT RUN: python outside.py --week3 --only w37_jieun_roof; review by eye (identity, "
      "no second person rendered, women only, dusk light); then checkpoint.py.")
  },
  {
    "id": "w37_market_peaches",
    "tier": 1,
    "lanes": ["instagram"],
    "media_file": MKT,
    "caption_file": None,
    "publish_at": "2026-09-12T10:15+09:00",
    "render_approved": False,
    "renders_available": 1,
    "reason": ("RENDER EXISTS BUT UNREVIEWED — generated by the batch-2 run that died before "
      "its review. This session's model has no image support, so the two gates could not be "
      "checked by eye: (1) the Korean price card must be unreadable or out of frame, "
      "(2) the two background figures must read as women. Spec hardened 7 Sep (the price-card "
      "writing is now specced too small and loose to read) so a re-roll has a better chance "
      "if this render fails either gate. Do not approve without eyes on it.")
  },
  {
    "id": "w37_table_sunday",
    "tier": 1,
    "lanes": ["instagram"],
    "media_file": None,
    "caption_file": None,
    "publish_at": "2026-09-13T21:05+09:00",
    "render_approved": False,
    "renders_available": 0,
    "reason": ("RE-SPECIFIED 7 Sep: now the third face frame of the week (owner 3-faces ruling) "
      "— arm's-length selfie at the table at night, NOT studio_after. Absolute gates carried in "
      "the spec: laptop screen turned away from the lens (only its back and a thin glow in "
      "frame), the single pencil line too faint to read, no readable numerals anywhere, lamp "
      "on, night outside the window. NOT GENERATED: never rendered by the killed batch-2 run, "
      "and this session's model has no image support, so generating now would produce an "
      "unreviewable render. Spec final and dry-run validated (plate_room, selfie=True, "
      "safe=True). NEXT RUN: python outside.py --week3 --only w37_table_sunday; check every "
      "gate by eye; then checkpoint.py.")
  },
]

j["blocked_note"] = ("4 of 7 are approved and shippable (class_bad, gimbap, fan, studio_after). "
  "The three blocked share one reason plus their own: NO RENDER APPROVED THIS RUN, because "
  "this session's model cannot see images (harness-confirmed), and every approval gate is "
  "visual. jieun_roof: old render deleted as spec-superseded, new face-in spec staged and "
  "dry-run validated. market_peaches: render on disk, needs an eye on the price card and the "
  "background figures. table_sunday: never generated; face-in spec staged and validated. "
  "Echo may queue the four entries; nothing else in this file is publishable.")

# ---- 3. generation meta, truthful ----
j["generation"] = {
  "model": "gpt-image-2-image-to-image",
  "provider": "kie",
  "images_generated": 7,
  "images_this_run": 0,
  "spend_usd": 0.63,
  "spend_this_run": 0.00,
  "spend_to_date_week": 0.63,
  "rerolls": 1,
  "account_credit_seen": 270.03,
  "approved": 4,
  "batch": 3,
  "note": ("Batch 1 (6 Sep): 4 images $0.36, 3 approved, 1 fan reroll (loser deleted). "
    "Batch 2 (killed by duration quota): studio_after generated, approved and checkpointed "
    "(running total 5 imgs / $0.45 per the last recorded checkpoint), then jieun_roof and "
    "market_peaches generated (7 imgs / $0.63) but the run died before their review. "
    "Cumulative figures are reconstructed from disk plus the last recorded checkpoint; "
    "same-name overwrites by the dead run, if any, would not show as extra files. "
    "Batch 3 (this run, 7 Sep): 0 images, $0.00 — spec work only. jieun_roof re-specced "
    "face-in per the owner 3-faces ruling and its cups-only render deleted as "
    "spec-superseded (its $0.09 stays in the cumulative total); table_sunday re-specced as "
    "the third face frame; market_peaches price-card legibility hardened in the spec. All "
    "three specs dry-run validated at zero cost. No generation this run: the session's model "
    "has no image support, so nothing generated could have been reviewed or approved. "
    "Credit re-read this run (free status call): 270.03."),
}

# ---- 4. blockers list: the live one first, carry the still-true ones ----
j["blockers"] = [
  ("SESSION CAPABILITY — THIS RUN'S MODEL CANNOT SEE IMAGES (harness-confirmed on every "
   "attempted image read). Every W37 approval gate is visual (identity, room continuity, "
   "screen angle, numeral and price-card legibility, gender of background figures), so "
   "nothing could be approved and nothing was generated — spending on unreviewable renders "
   "would recreate the unreviewed-render state that stalled this week. A vision-capable run "
   "finishes the week with: outside.py --week3 --only <id>, eye review, checkpoint.py, "
   "gen_meta.py --stats. About $0.27 remains to finish all three blocked shots at one "
   "render each, well inside the $2.00 batch-3 budget."),
  ("PIPELINE GAP — outside.py has --week3 but no console.POOLS row, so weekly_prep.py does "
   "not audit this pool yet. Not fixed here: console and outside.py are shared code, "
   "outside my lane."),
  ("PLATE GAPS — plate_kitchen and plate_window still do not resolve; the only single-file "
   "kitchen/window plates are under locations/_superseded_rich_flat/ (a different flat, "
   "off-limits). No kitchen or window-anchor frame is possible this week without an owner "
   "decision on locations/."),
  ("CONFIG vs CODE MISMATCH — exclude_body_ref does not exist in the repo. The real "
   "mechanism is body=True / limb=True attaching master/c/c5_relax_front.png; clothed-torso "
   "shots set neither flag and never say 'tattoo'."),
  ("NOT READ, BY INSTRUCTION — playbook.md, offline/, growth/COMPLIANCE.md, archive/, "
   "PIPELINES.md §5 (tattoo rendering rules), growth/RUNBOOK.md."),
]

# ---- 5. verified: carry forward what still holds; drop the stale batch-1 line ----
j["verified"] = [v for v in j.get("verified", []) if not v.startswith("BATCH 1 RENDERED")]
j["verified"].append(
  ("DISK TRUTH 7 SEP (batch 3, post-reconcile): 5 renders in the pool — the 4 approved "
   "entries plus w37_market_peaches_421923_1.png (unreviewed, see blocked). Every entry's "
   "media_file and caption_file exist on disk, and handoff captions for the approved shots "
   "are byte-identical to the caps/*.txt files. w37_jieun_roof_bd67ba_1.png deleted: it was "
   "generated from the noface spec and cannot satisfy the face-in rebalance."))
j["verified"].append(
  ("SPECS STAGED AND DRY-RUN VALIDATED (batch 3, $0.00): w37_jieun_roof (face-in, "
   "friend-taken per the n_cafe_jieun precedent, Jieun implied by the second cup, never "
   "rendered; plate_rooftop; safe=True), w37_table_sunday (face-in selfie, the third face "
   "frame, laptop back to the lens, pencil line too faint to read; plate_room; selfie=True), "
   "w37_market_peaches (price-card writing specced too small and loose to read). "
   "outside.py --week3 --only <all three> --dry-run assembles each prompt correctly: plate "
   "as Image 1, her face as Images 2-3, ARMS appended on the selfie only."))
j["verified"].append(
  ("JIEUN PRECEDENT CONFIRMED FROM SHIPPED WORK: n_cafe_jieun (grid, week 1) is taken BY "
   "Jieun — she is behind the camera, implied only by the second glass nearest the lens, "
   "and she has never been rendered in any shipped frame. The re-specced w37_jieun_roof "
   "follows exactly this. No Jieun reference image exists and none may be invented."))

HF.write_text(json.dumps(j, ensure_ascii=False, indent=2) + "\n",
              encoding="utf-8", newline="\n")
print("written. entries:", len(j["entries"]), "blocked:", len(j["blocked"]),
      "gen:", j["generation"]["images_generated"], j["generation"]["spend_usd"])
